### ISSUE TITLE
camelCase for the "mount" of UMDs

### ISSUE THREAD

**Issue by tunnckoCore** [lukeed/bundt#2]
Currently if name has dashes or is scoped one, used must use `window['@foo/bar-qux']` which isn't looking good at all. With making it camelCase it is a lot better and intuitive too.

```js
function snakeToCamel(str) {
  return  str.replace(/([-_][a-z])/g, group =>
    group
      .toUpperCase()
      .replace('-', '')
      .replace('_', '')
  );
}

function safePackageName(str) {
  return snakeToCamel(str.replace('@', '').replace('/', '.'));
}

const name = pkg['umd:name'] || pkg.name;
const mount = `.${safePackageName(name)}`
```

**Comment by lukeed** [comment]
That's the name you picked.

If you don't want to use `name` (from package.jsom) then you can choose another with `umd:name` - here's [an example](https://github.com/lukeed/uuid/blob/master/package.json#L11)

Hope that helps!

**Comment by tunnckoCore** [comment]
I know. But `umd:name` is ugly (not to mention if you have Prettier package.json formatting), first; and second - for better defaults.

**Comment by lukeed** [comment]
Nope, thats what it's there for

I didn't name the key, it was already a convention
